
import { Providers } from "./providers";
import { Inter } from "next/font/google";
import "./globals.css";
// import { StateProvider } from "./context/state";


//const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` body `}>
      {/* <StateProvider> */}
      <Providers>{children}</Providers>
      {/* </StateProvider> */}
      
        </body>
    </html>
  );
}
